[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
    # directories
    \.eggs
  | \.git
  | \.venv
  | data
  | jupyter-notebooks
)/
'''

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Relax for research code
ignore_missing_imports = true
exclude = [
    "data/",
    "jupyter-notebooks/",
    "venv/",
]